parameters:
  oxid_esales.utility.hash.service.password_hash.algo: !php/const PASSWORD_BCRYPT
  oxid_esales.utility.hash.service.password_hash.options:
    - { cost: 10 }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Domain\Authentication\Service\PasswordHashServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Authentication\Service\PasswordHashService
    arguments:
      - '%oxid_esales.utility.hash.service.password_hash.algo%'
      - '%oxid_esales.utility.hash.service.password_hash.options%'

  OxidEsales\EshopCommunity\Internal\Domain\Authentication\Bridge\PasswordServiceBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Authentication\Bridge\PasswordServiceBridge
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Authentication\Service\PasswordVerificationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Authentication\Service\PasswordVerificationService

  OxidEsales\EshopCommunity\Internal\Domain\Authentication\Policy\PasswordPolicyInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Authentication\Policy\PasswordPolicy
