services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\ShopAdapterInterface:
    class: OxidEsales\EshopCommunity\Internal\Transition\Adapter\ShopAdapter

  OxidEsales\EshopCommunity\Internal\Framework\Config\Dao\ShopConfigurationSettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Config\Dao\ShopConfigurationSettingDao

  OxidEsales\EshopCommunity\Internal\Framework\Config\Utility\ShopSettingEncoderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Config\Utility\ShopSettingEncoder

  # TemplateLogic
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\AddUrlParametersLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\ContentFactory:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\DateFormatHelper:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FileSizeLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatCurrencyLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatDateLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatPriceLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatTimeLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IfContentLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IncludeDynamicLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IncludeWidgetLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\InputHelpLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\InsertNewBasketItemLogicSmarty:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\InsertNewBasketItemLogicTwig:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\ScriptLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\SeoUrlLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\SmartWordwrapLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\StyleLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateFilterLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateFunctionLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateSalutationLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TruncateLogic:
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\WordwrapLogic:
