imports:
    - { resource: ConfigFile/services.yaml }
    - { resource: Database/services.yaml }
    - { resource: Directory/services.yaml }
    - { resource: Htaccess/services.yaml }
    - { resource: Language/services.yaml }
    - { resource: Command/services.yaml }
