imports:
    - { resource: Bridge/services.yaml }
    - { resource: Dao/services.yaml }
    - { resource: Factory/services.yaml }
    - { resource: Service/services.yaml }
    - { resource: Command/services.yaml }